version: '3'
services:
  siege:
    image: 'yokogawa/siege'
    volumes:
      - ./log:/var/log:rw
    network_mode: host
    entrypoint: ["siege","-d1", "-r10", "-c25", "http://localhost:8000/apache1"]
    